# a_tensor_initialization

In [2]:
import torch

In [3]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


- 위 코드에서 torch.tensor() 함수는 주어진 리스트내 원소 타입을 그대로 유지시켜 준다.

# b_tensor_initialization_copy

In [32]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 =[1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 50)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)    # numpy 배열 as_tensor만 공유됨

l4[0] = 100
l4[1] = 100
l4[2] = 100

print(t4)
print(t5)
print(t6)


print("#" * 50)

# t를 수정하면 l도 변경되고, l을 수정하면 t가 변경되는지 확인
t4[0] = 100
t5[0] = 100
t6[0] = 100

print(l6)
print()

l4[0] = 1
l5[0] = 1
l6[0] = 1

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
##################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
##################################################
[100   2   3]

tensor([100.,   2.,   3.])
tensor([100,   2,   3])
tensor([1, 2, 3])


# c_tensor_initialization_constant_values

In [46]:
import torch
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)
print(t1)
print(t1_like)

t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

t4 = torch.eye(n=3)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values

In [50]:
import torch

t1 = torch.randint(low=10, high=20, size=(1,2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3,2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[16, 11]])
tensor([[0.1148, 0.0016, 0.6302]])
tensor([[1.3831, 1.1416, 0.2294]])
tensor([[10.0868, 11.3466],
        [ 9.9522,  9.5417],
        [ 9.7490,  8.9550]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

In [61]:
import torch

a = torch.ones((2,3))
print(a.dtype)
# print(a)

b = torch.ones((2,3), dtype=torch.int16)
print(b)

c = torch.rand((2,3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1,2]], dtype=torch.short)

double_d = torch.zeros(10,2).double()
short_e = torch.ones(10,2).short()

double_d = torch.zeros(10,2).to(torch.double)
short_e = torch.ones(10,2).to(dtype=torch.short)

double_d = torch.zeros(10,2).type(torch.double)
short_e = torch.ones(10,2).type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 1.8129, 16.9121,  6.2997],
        [14.3661,  0.2442, 18.7508]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16


# f_tnesor_operations

In [68]:
import torch

t1 = torch.ones(size=(2,3))
t2 = torch.ones(size=(2,3))
t3 = torch.add(t1,t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1,t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1,t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1,t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

In [72]:
import torch

t1 = torch.dot(
    torch.tensor([2,3]), torch.tensor([2,1])
)
print(t1, t1.size())

t2 = torch.randn(2,3)
t3 = torch.randn(3,2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5,t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[ 0.4511, -1.7412],
        [-0.2824,  0.6300]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


# h_tensor_operations_matmul

In [80]:
import torch

t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1,t2).size())

t3 = torch.randn(3,4)
t4 = torch.randn(4)
print(torch.matmul(t3,t4).size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5,t6).size())

t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7,t8).size())

t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4,5)
print(torch.matmul(t9,t10).size())

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


# i_tensor_broadcasting

In [101]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0,1], [2,4], [10,10]])
t4 = torch.tensor([4,5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

print("#" * 50, 3)

def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3,2)
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3,1)
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1,2)
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)

t28 = torch.pow(t27, 2)
print(t28)

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

# j_tensor_indexing_slicing

In [116]:
import torch

x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1])
print(x[:, 1])
print(x[1, 2])
print(x[:, -1])

print("#" * 50, 1)

print(x[1:])
print(x[1:, 3:])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping

In [145]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)      # 메모리를 공유 / 요소들의 수 일치해야 함
t3 = t1.reshape(1, 6)   # 메모르 공유X 얕은 복사 / 요수들의 수 일치 안해도 됨
print(t2)
print(t3)

print("#" * 50, 1)

t4 = torch.arange(8).view(2, 4)
t5 = torch.arange(6).view(2, 3)
print(t4)
print(t5)

print("#" * 50, 2)

t6 = torch.tensor([[[1], [2], [3]]])
print(t6)

t7 = t6.squeeze()   # squeeze : 차원 제거 / dim 지정 하지 않을 경우 모든 크기가 1인 차원 제거

t8 = t6.squeeze(0)
print(t7)
print(t8)

print("#" * 50, 3)

t9 = torch.tensor([1, 2, 3])

t10 = t9.unsqueeze(1)
print(t10)

t11 = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]]
)
# print(t11.shape) # >> torch.Size([2, 3])
t12 = t11.unsqueeze(1)
print(t12, t12.shape)

print("#" * 50, 4)

t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t14 = t13.flatten()

print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 5)

t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))
print(t20)
print(t21)

print("#" * 50, 6)

t22 = torch.transpose(t19, 0, 1)

print(t22)

t23 = torch.t(t19)

print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
################################################## 1
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 2
tensor([[[1],
         [2],
         [3]]])
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 3
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 4
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 5
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
################################################## 6
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2

# l_tensor_concat

In [164]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4. shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)
print("t5: ", t5.shape)
print("t6: ", t6.shape)

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
print(t7)

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())
print(t11)

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)
print(t17)
print(t18)

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())
print(t19, "\n")

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())
print(t20, "\n")

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())
print(t21)

torch.Size([2, 6, 3])
################################################## 1
t5:  torch.Size([3])
t6:  torch.Size([5])
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 4
tensor([[[0, 1, 2],
         [3, 4, 5]]])
tensor([[[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]]) 

torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]]) 

torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking

In [172]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim =0)
print(t2.shape, t3.equal(t4))
print(t3)

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([2, 3]) True
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


In [179]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
t7 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9.shape)

print(t9)

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])

print(t16.shape)

t17 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)

print(t18)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])
